### ISSUE TITLE
MMA generates wrong Regex in HttpRequester and HttpListerener DWL File

### ISSUE THREAD

**Issue by holiday-sunrise** [mulesoft/mule-migration-assistant#408]
Hi Togehter,

we @OBI try to use the MMA but it Fails.

Step to reproduce.

1. Create Mule3 Project with APIKit
2. Add HTTP Request in a Flow
3. Run MMA

Import the Project in Studio 7.5.1

2 Files have Failures.

```
fun httpRequesterHeaders(vars: {}) = do {
    var matcher_regex = /(?i)http\..*|Connection|Host|Transfer-Encoding/. **<-- Failure** 
    ---
    vars.compatibility_outboundProperties filterObject
        ((value,key) -> not ((key as String) matches matcher_regex))
        mapObject ((value, key, index) -> {
            (if (upper(key as String) startsWith 'MULE_') upper('X-' ++ key as String) else key) : value
        })
}
```

```
/**
 * Emulates the response headers building logic of the Mule 3.x HTTP Connector.
 */
fun httpListenerResponseHeaders(vars: {}) = do {
    var matcher_regex = /(?i)http\..*|Connection|Transfer-Encoding/.     **<-- Failure** 
    ---
    vars.compatibility_outboundProperties default {} filterObject
        ((value,key) -> not ((key as String) matches matcher_regex))
        mapObject ((value, key, index) -> {
            (if (upper(key as String) startsWith 'MULE_') upper('X-' ++ key as String) else key) : value
        })
}

```

Multiple markers at this line
- no viable alternative at input '..'
- no viable alternative at input ')'
- missing '}' at '*'
- no viable alternative at input '?'
- no viable alternative at input '/'

Whats wrong its generated 

Kind regards

rainer

**Comment by machaval** [comment]
Hi, 

```dataweave
/**
 * Emulates the response headers building logic of the Mule 3.x HTTP Connector.
 */
fun httpListenerResponseHeaders(vars: {}) = do {
    var matcher_regex = /(?i)http\..*|Connection|Transfer-Encoding/
    ---
    vars.compatibility_outboundProperties default {} filterObject
        ((value,key) -> not ((key as String) matches matcher_regex))
        mapObject ((value, key, index) -> {
            (if (upper(key as String) startsWith 'MULE_') upper('X-' ++ key as String) else key) : value
        })
}
---
{}
```
This code is valid maybe there is an issue in studio saying it is not. But it will execute ok and the runtime is going to be able to parse it.  Please open the ticket to Studio product. I saw an extra dot at the end of your regex I assume you add it if not then that is the problem.

**Comment by julianpascualMuleSoft** [comment]
Yes, @machaval is right. I've just tested the migration and the script is correctly generated (doesn't contain that dot) and it also executes fine on the runtime.
It's an issue on Studio side that marks the expression as wrong.

**Comment by holiday-sunrise** [comment]
The "Dot" behind the Line was my failure.   if you double klick in a editor it adds an Dot.  I will create an Case for that. Thx for your help.

**Comment by holiday-sunrise** [comment]
Mule Case Number 00260413

**Comment by pentreathm** [comment]
I'll close this issue as the scope of the fix is out of MMA and will be follow on the Mule case.
