### ISSUE TITLE
Needs to manually fix global elements for various connectors like HTTP, WSC, APIKit and so on

### ISSUE THREAD

**Issue by github-amitpandey** [mulesoft/mule-migration-assistant#447]

**Comment by pentreathm** [comment]
Hi @github-amitpandey, what do you mean by manually fix? 
There are always manual fixes needed in the migration process but is there anything that is being generated wrongly? 
Can you please add examples?

**Comment by afelisatti** [comment]
Hi, @github-amitpandey. Thanks for reporting this. Unfortunately, we cannot analyze the issue further without an example of the problem. Please feel free to reopen the issue with an example that demonstrates how the assistant is working and your expectations on how it should behave. Cheers!
