### ISSUE TITLE
Instances of "payload" in WSC response transform were changed to "payload.body" due to Mule 4 structure.

### ISSUE THREAD

**Issue by github-amitpandey** [mulesoft/mule-migration-assistant#448]

**Comment by pentreathm** [comment]
Hi @github-amitpandey - could you please further explain what's the issue that you are facing? 
Please also try to isolate a sample Mule 3 app and add the result so that the issue can be reproduced and investigated.

**Comment by afelisatti** [comment]
Hi, @github-amitpandey. Thanks for reporting this. Unfortunately, we cannot analyze the issue further without an example of the problem. Please feel free to reopen the issue with an example that demonstrates how the assistant is working and your expectations on how it should behave. Cheers!
