### ISSUE TITLE
SOAPKIT Router not passing the header in case of failure

### ISSUE THREAD

**Issue by github-amitpandey** [mulesoft/mule-migration-assistant#450]

**Comment by pentreathm** [comment]
Hi @github-amitpandey , could you explain a little more what's going on with this? 
Can you please try to isolate the issue in a simple Mule 3 app and add the sample so that it can be reproduce?

**Comment by afelisatti** [comment]
Hi again, @github-amitpandey. Thanks for reporting this. Unfortunately, we cannot analyze the issue further without an example of the problem. Please feel free to reopen the issue with an example that demonstrates how the assistant is working and your expectations on how it should behave. Cheers!
