### ISSUE TITLE
Response element (<response>) causes StackOverflow when used above Apikit router

### ISSUE THREAD

**Issue by SlightlyDave** [mulesoft/mule-migration-assistant#456]
Hi,

When running the migrator for a project that contains <response></response> elements which are placed in the entry point into the API just before the apikit element causes a java.lang.StackOverflowError, removing these tags from the source API allows the migration tool to complete correctly.

The command line that was used:

`java -jar mule-migration-assistant-runner-1.1.0.jar -projectBasePath C:\MuleSoft\Mule3to4Projects\Mule3Api -parentDomainBasePath C:\MuleSoft\Mule3to4Projects\Mule3Domain -muleVersion 4.3.0 -destinationProjectBasePath C:\MuleSoft\Mule4Projects\Mule4Api`

Example Code:

` <flow name="api-main">
    	
        <http:listener config-ref="Ref" path="${api.http.listener.path}" doc:name="HTTP" >
        </http:listener>

        <set-property propertyName="vTimeStamp" value="#[server.dateTime.format('YYYY-MM-dd HH:mm:ss,S')]" doc:name="Set TimeStamp"/>
        
		<response>
			<set-property propertyName="vTimeStamp" value="#[server.dateTime.format('YYYY-MM-dd HH:mm:ss,S')]" doc:name="Set TimeStamp"/>
		</response>

        <apikit:router config-ref="api-config" doc:name="APIkit Router" />
        <exception-strategy ref="global-exception-strategy" doc:name="Reference Exception Strategy" />
    </flow>`

Command output:

`Executing migrator 1.1.0...
Exception in thread "main" java.lang.StackOverflowError
	at org.jdom2.Content.getDocument(Content.java:231)
	at org.jdom2.Content.getDocument(Content.java:231)
	at com.mulesoft.tools.migration.step.util.XmlDslUtils.isTopLevelElement(XmlDslUtils.java:501)
	at com.mulesoft.tools.migration.library.apikit.steps.ApikitHttpListenerMapping.getParentFlow(ApikitHttpListenerMapping.java:95)
	at com.mulesoft.tools.migration.library.apikit.steps.ApikitHttpListenerMapping.getParentFlow(ApikitHttpListenerMapping.java:103)
	at com.mulesoft.tools.migration.library.apikit.steps.ApikitHttpListenerMapping.getParentFlow(ApikitHttpListenerMapping.java:103)`

Last line repeats 1020 times.

**Comment by holiday-sunrise** [comment]
Same to us

**Comment by mlischetti** [comment]
Hi @SlightlyDave the example code seems to be broken. 
Can you please try to isolate the issue in a simple Mule 3 app and add the example to the issue so that it can be reproduced?

**Comment by holiday-sunrise** [comment]
[migration.log](https://github.com/mulesoft/mule-migration-assistant/files/6932021/migration.log)
[mma-456-test-api.zip](https://github.com/mulesoft/mule-migration-assistant/files/6932028/mma-456-test-api.zip)

MMA Snapshot 1.1.1 Master Branch

**Comment by afelisatti** [comment]
Thanks, @holiday-sunrise! The app is consistent with what we observed. We will review your pull request soon.
