### ISSUE TITLE
add "catalog" Folder to Exclusions

### ISSUE THREAD

**Issue by holiday-sunrise** [mulesoft/mule-migration-assistant#463]
the folder "catalog" have to be excluded

**Comment by mlischetti** [comment]
@holiday-sunrise that's right.
Feel free to send a PR adding Catalog folder into [Exclusions](https://github.com/mulesoft/mule-migration-assistant/blob/867730fec90f55b568a75fdd3fdfc95bb7cdc994/mule-migration-tool-engine/src/main/java/com/mulesoft/tools/migration/engine/project/structure/util/Exclusions.java#L21)

**Comment by holiday-sunrise** [comment]
see pull request https://github.com/mulesoft/mule-migration-assistant/pull/474

**Comment by mlischetti** [comment]
Hi 
That PR includes 2 changes:
 - catalog folder was added to exclusions enum
 - .gitignore file was removed from exclusions enum
Current issue is about catalog folder so a PR to fix this issue should only include changes related with catalog folder.
