### ISSUE TITLE
increase development version

### ISSUE THREAD

**Issue by holiday-sunrise** [mulesoft/mule-migration-assistant#467]
Release 1.1.0 was build. See Tag 

Set Next DevelopmentVersion 1.2.0-SNAPSHOT

FIX.: mvn versions:set -DnewVersion=1.2.0-SNAPSHOT -DprocessAllModules -DgenerateBackupPoms=false

**Comment by mlischetti** [comment]
Hi @holiday-sunrise thanks for report this issue.
You're right there was a mistake setting current development version.
We've changed to 1.1.1-SNAPSHOT

**Comment by holiday-sunrise** [comment]
why did you set the version 1.1.1-SNAPSHOT know we have several merg conflicts. Mirco are bug fixes not improvements.

**Comment by afelisatti** [comment]
Hi, @holiday-sunrise! We decided to bump the patch version until we identify new features or changes that require a minor version bump. We apologize for any inconvenience!
