### ISSUE TITLE
ValidationMigrationTask won't migrate matches-regex 

### ISSUE THREAD

**Issue by holiday-sunrise** [mulesoft/mule-migration-assistant#494]
Mule3 API with the following validation
`<validation:matches-regex message="[API Message]: Status is #[flowVars.httpStatusFromPayload]. Expected 200" exceptionClass="java.lang.Exception" value="#[flowVars.httpStatusFromPayload]" regex="200" doc:name="Throw Exception Message"/>`

Mule4 API after the migration.

` <validation:matches-regex message="[API Message]: Status is #[flowVars.httpStatusFromPayload]. Expected 200" exceptionClass="java.lang.Exception" value="#[vars.httpStatusFromPayload]" regex="200" doc:name="Throw Exception Message" />`
               

Message is not migrated

**Comment by afelisatti** [comment]
Hi, @holiday-sunrise! This looks like a known gap: the `message` attribute uses a template (text with embedded expressions). Templates in Mule 4 are supported by a handful of components like the logger and parse template, but not the matches-regex operation. 
We will review the feasibility of supporting the migration of templates. If it helps, the migrated value should be:
```
message="#['[API Message]: Status is $(vars.httpStatusFromPayload). Expected 200']"
```

**Comment by holiday-sunrise** [comment]
It works fine if we migrate it by hand
