### ISSUE TITLE
.gitignore is not migrated.  A new Mule4/Studio 7 dependent should be created during migration

### ISSUE THREAD

**Issue by holiday-sunrise** [mulesoft/mule-migration-assistant#508]
The Exclusion `GIT(File.separator + ".gitignore")` did not copy the file in the target directory. Thats ok because its Mule3 dependent 

Enhancement Post Migration Step should create a .gitignore file like you starting a new project with studio 7.x

**Comment by holiday-sunrise** [comment]
hi ana,

what did you think

kind regards

rainer

**Comment by afelisatti** [comment]
Hi, @holiday-sunrise. Thanks for this contribution. This seems like a step in the right direction until we implement a "merge" of the Studio 7 ignores and the Mule 3 existing file. I'll get a review from some Studio experts in case we are missing something.

**Comment by holiday-sunrise** [comment]
The mule3 file will be ignored and the org. Studio 7.10 !!! File will be used. Same source

**Comment by holiday-sunrise** [comment]
Should he review that I am able to copy a file 😂

**Comment by afelisatti** [comment]
I think it will be fine. It's just in case we are missing some other task Studio 7 runs.
