### ISSUE TITLE
Add support for parent pom migration

### ISSUE THREAD

**Issue by afelisatti** [mulesoft/mule-migration-assistant#516]
If an app to migrate has a parent pom (to handle organization-wide dependencies, for example), users have to either code their own migration step or add the parent after.
It would be great to add a configuration that takes this into account when executing, so the migrated pom includes the parent from the get-go without any extra effort.

**Comment by holiday-sunrise** [comment]
Mybe we can add a yml file with some configurations ?!? So the Step can migrate the parent entry. 

What did you mean ?

**Comment by afelisatti** [comment]
I was thinking it should be part of the execution configuration, such as an optional parameter with the GAV (groupId, artifactId, and version) of the parent to use.

**Comment by holiday-sunrise** [comment]
i will add a step so we can discuss about the implementation

**Comment by afelisatti** [comment]
That'd be great. My thinking is: if the step is essentially adding the parent with a certain groupId, artifactId, and version, then we could parameterize those. From the command line, you could indicate those values and we would have parent pom support without extra code.

**Comment by holiday-sunrise** [comment]
Should i implement one option like "projectParentGAV" 

`-projectParentGroupId com.obi.smartgate -projectParentArifactId rest-parent -projectParentVersion 2.0.0`

or three options e.g.

`-projectParentGAV com.obi.smartgate:rest-parent:2.0.0`

**Comment by holiday-sunrise** [comment]
see https://github.com/mulesoft/mule-migration-assistant/pull/529

**Comment by afelisatti** [comment]
Thanks for your contribution, @holiday-sunrise !!!

**Comment by holiday-sunrise** [comment]
You are welcome
