### ISSUE TITLE
Response element migration does not account for error handling

### ISSUE THREAD

**Issue by afelisatti** [mulesoft/mule-migration-assistant#530]
Response elements should be added as the last elements of a flow when migrated. However, this should consider that if the flow has error handling, then that component will be the last so the response elements should be added before it.
The current behavior generates invalid applications that fail on deployment since no elements are expected after the error handler:
Mule 3 flow:
```
    <flow name="simpleFlow">
        <response>
            <logger message="in response"/>
        </response>
        <logger/>
        <catch-exception-strategy when="#[exception.causedBy(java.lang.IllegalStateException)]">
            <logger message="#['IlegalState']" />
        </catch-exception-strategy>
    </flow>
```
Migrated Mule 4 result (fails to deploy):
```
    <flow name="simpleFlow">
        <try>
            <logger/>
        </try>
        <error-handler>
            <on-error-continue when="#[Java::isCausedBy(error.cause, 'java.lang.IllegalStateException', false)]">
                <logger message="#['IlegalState']" />
            </on-error-continue>
        </error-handler>
        <logger message="in response"/>
    </flow>
```

**Comment by holiday-sunrise** [comment]
may you add a example application. did you have an idea in which step the failure occurs
