### ISSUE TITLE
Unsupported SFDC configuration does not produce any errors

### ISSUE THREAD

**Issue by afelisatti** [mulesoft/mule-migration-assistant#564]
**Version used**
1.2.0

**Describe the bug**
When a deprecated component from the Salesforce connector is handled by the tool, it remains as is instead of being commented and generating a report entry saying it's unsupported.

***Expected Behavior***
An ERROR report entry should be generated explaining it's not supported and the code commented to avoid invalid Mule 4 content.

***Actual Behavior***
This config remains the same, with no report entries:
```
<sfdc:config-oauth-user-pass name="Salesforce__Basic_Authentication"
                consumerKey="${sfdc.consumerkey}" consumerSecret="${sfdc.consumersecret}"
                username="${sfdc.username}" password="${sfdc.password}"
                securityToken="${sfdc.securitytoken}" tokenEndpoint="${sfdc.authurl}"
                doc:name="ct_salesforce" readTimeout="${sfdc.read.timeout}"
                disableSessionInvalidation="true">
                <reconnect count="${sfdc.reconnect.attemptcount}"
                        frequency="${sfdc.reconnect.frequency}" />
        </sfdc:config-oauth-user-pass>
```

**Reproducible Test Case**
I haven't tried reproducing the error. I think the most concerning part is that there seems to be a mechanism to automatically report and comment components when their namespace is unknown but nothing for this scenario where the namespace is known but the element isn't.

**Comment by jesica-fera** [comment]
This issue has been fixed by the associated PR
