### ISSUE TITLE
"Format Doesn't Match" Exception on Compile

### ISSUE THREAD

**Issue by suez-ahmeda** [mulesoft/mule-migration-assistant#615]
**Version used**
1.2.0

**Describe the bug**
Version 1.2.0 fails to compile with a "Format doesn't match" exception. Previous versions compile successfully, however v1.2.0 is the only one with the -jsonReport argument, so we need this version.

***Expected Behavior***
Successful compile, similar to previous versions.

***Actual Behavior***
"Format doesn't match" exception is thrown.

**Relevant logs**
[mma-error-logs.txt](https://github.com/mulesoft/mule-migration-assistant/files/8571774/mma-error-logs.txt)

**Comment by svacas** [comment]
I guess the problem may be the line endings not matching the target OS, for Windows it expects CRLF.
you can run maven with this to reformat the code: `-DformatterGoal=format`

**Comment by suez-ahmeda** [comment]
That got it working. Thanks.
