### ISSUE TITLE
not able to run MMA report 

### ISSUE THREAD

**Issue by piyushmishra2103** [mulesoft/mule-migration-assistant#754]
Hi Team, We need to migrate from EOL Mule version 3.9 to 4.x. When using the MMA tool, following error shown is: C:\Vorwerk\MMA\mule-migration-assistant\runner\target>java -jar mule-migration-assistant-runner-1.4.1-SNAPSHOT.jar -muleVersion 4.3.0 -projectBasePath \Users\mattab\AnypointStudio_2\mule_pl_from_zip\mule_imported -destinationProjectBasePath \Vorwerk\GIT_Intelij\migrated-mule\migration_5 Executing migrator 1.4.1-SNAPSHOT... =============================================================================== MIGRATION FAILED =============================================================================== Total time: 0,815 s Exception: Cannot read mule project. Is it a Mule Studio project? com.mulesoft.tools.migration.engine.exception.MigrationJobException: Cannot read mule project. Is it a Mule Studio project? at com.mulesoft.tools.migration.engine.project.MuleProjectFactory.getMuleProject(MuleProjectFactory.java:49) at com.mulesoft.tools.migration.engine.MigrationJob.generateSourceApplicationModel(MigrationJob.java:159) at com.mulesoft.tools.migration.engine.MigrationJob.execute(MigrationJob.java:96) at com.mulesoft.tools.migration.MigrationRunner.run(MigrationRunner.java:92) at com.mulesoft.tools.migration.MigrationRunner.main(MigrationRunner.java:77) Can you please assist us, Thanks

**Comment by martincousido** [comment]
Hi @piyushmishra2103 please check this guide here:
https://github.com/mulesoft/mule-migration-assistant/blob/c4e3c7621dfe91e53cbb4abce6840c85f0c029b8/docs/user-docs/migration-tutorial.adoc#step-2-create-a-mule-4-app-from-the-mule-3-app
It seems that you are running on Windows and there is a note on that same error you are encountering, please try the steps mentioned there and feel free to reopen if you find the error still persists.
